# Generated by Django 4.2 on 2023-04-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('prestataire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
    ]
