# Generated by Django 4.2 on 2023-04-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataire', '0002_prestataire_is_active_alter_prestataire_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidaturePrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('message', models.TextField(max_length=2048)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
