# Generated by Django 4.2 on 2023-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataire', '0003_candidatureprestataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatureprestataire',
            name='justificatif',
            field=models.ImageField(null=True, upload_to='pictures/justificatifs-candidature/'),
        ),
        migrations.AlterField(
            model_name='candidatureprestataire',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
